# Generated by Django 3.0.3 on 2020-05-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('areaId', models.AutoField(primary_key=True, serialize=False)),
                ('areaName', models.CharField(default='', max_length=30)),
                ('areaDescription', models.CharField(default='', max_length=200)),
                ('cityId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(default='', max_length=30)),
                ('cityDescription', models.CharField(default='', max_length=200)),
                ('stateId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(default='', max_length=30)),
                ('stateDescription', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
