# Generated by Django 3.0.3 on 2020-05-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0002_area_city_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='areaActive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='cityActive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='stateActive',
            field=models.IntegerField(default=0),
        ),
    ]
