# Generated by Django 3.0.3 on 2020-05-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0003_auto_20200511_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruits',
            fields=[
                ('fruitId', models.AutoField(primary_key=True, serialize=False)),
                ('fruitName', models.CharField(default='', max_length=25)),
                ('fruitDescription', models.CharField(default='', max_length=200)),
                ('fruitImage', models.CharField(default='', max_length=200)),
                ('fruitMarketPrice', models.FloatField(default=0.0)),
                ('fruitOurPrice', models.FloatField(default=0.0)),
                ('fruitWeight', models.FloatField(default=0.0)),
                ('catId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Vegis',
            fields=[
                ('vegiId', models.AutoField(primary_key=True, serialize=False)),
                ('vegiName', models.CharField(default='', max_length=25)),
                ('vegiDescription', models.CharField(default='', max_length=200)),
                ('vegiImage', models.CharField(default='', max_length=200)),
                ('vegiMarketPrice', models.FloatField(default=0.0)),
                ('vegiOurPrice', models.FloatField(default=0.0)),
                ('vegiWeight', models.FloatField(default=0.0)),
                ('catId', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='VFCategory',
            fields=[
                ('catId', models.AutoField(primary_key=True, serialize=False)),
                ('catName', models.CharField(default='', max_length=25)),
                ('catDescription', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
