# Generated by Django 3.0.3 on 2020-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0004_fruits_vegis_vfcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='fruitStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vegis',
            name='vegiStatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vfcategory',
            name='catStatus',
            field=models.IntegerField(default=0),
        ),
    ]
