# Generated by Django 3.0.3 on 2020-05-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0005_auto_20200513_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fruits',
            old_name='fruitWeight',
            new_name='fruitPricePerWeight',
        ),
        migrations.RenameField(
            model_name='vegis',
            old_name='vegiWeight',
            new_name='vegiPricePerWeight',
        ),
        migrations.AddField(
            model_name='fruits',
            name='fruitSKU',
            field=models.CharField(default='SKUF-1', max_length=20),
        ),
        migrations.AddField(
            model_name='fruits',
            name='fruitTotalStock',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='vegis',
            name='vegiSKU',
            field=models.CharField(default='SKUV-1', max_length=20),
        ),
        migrations.AddField(
            model_name='vegis',
            name='vegiTotalStock',
            field=models.FloatField(default=1),
        ),
    ]
