# Generated by Django 3.0.3 on 2020-05-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0006_auto_20200513_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='VegiFruits',
            fields=[
                ('vegifruitId', models.AutoField(primary_key=True, serialize=False)),
                ('vegifruitName', models.CharField(default='', max_length=25)),
                ('vegifruitDescription', models.CharField(default='', max_length=200)),
                ('vegifruitImage', models.CharField(default='', max_length=200)),
                ('vegifruitSKU', models.CharField(default='SKU-1', max_length=20)),
                ('vegifruitMarketPrice', models.FloatField(default=0.0)),
                ('vegifruitOurPrice', models.FloatField(default=0.0)),
                ('vegifruitPricePerWeight', models.FloatField(default=0.0)),
                ('catItd', models.IntegerField(default=1)),
                ('vegifruitTotalStock', models.FloatField(default=1)),
                ('vegifruitStatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruits',
        ),
        migrations.DeleteModel(
            name='Vegis',
        ),
    ]
