# Generated by Django 3.0.3 on 2020-05-13 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0007_auto_20200513_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vegifruits',
            old_name='catItd',
            new_name='catId',
        ),
    ]
