# Generated by Django 3.0.3 on 2020-05-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0008_auto_20200513_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userPasswordSecret',
            field=models.CharField(default='', max_length=16),
        ),
    ]
