# Generated by Django 3.0.3 on 2020-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VegiApp', '0009_user_userpasswordsecret'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('tokenId', models.AutoField(primary_key=True, serialize=False)),
                ('tokenAuth', models.CharField(default='kdkfjdkkfjkjdfkjfk', max_length=128)),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
